print("Please enter the following information:")
fname = input("First name: ")
lname = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ") 
id_number = input("ID number: ")
print()
#Additional Information
hair_color = input("Hair: ")
eye_color = input("Eyes: ")
month = input("Birth month: ")
training = input("Completed additional training? ")
print()

print("The ID card is: ")
print("------------------------------------------------------------")
print(f"{lname.upper()}, {fname.capitalize()}")
print(f"{job.title()}")
print(f"ID: {id_number}")
print()
print(email.lower())
print(phone)
print()

print(f"Hair: {hair_color:15} Eyes: {eye_color}")
print(f"Birth Month: {month:10} Training: {training}")
print("------------------------------------------------------------")
